package io.github.cdsap.daemonitor

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class BuildInfoTest {
    @Test
    fun `loads version commit and distribution generated by the build`() {
        val buildInfo = BuildInfo.current

        assertEquals("1.0.7", buildInfo.version)
        assertTrue(buildInfo.commit.matches(Regex("[0-9a-f]{7,40}|unknown")), buildInfo.commit)
        assertEquals(io.github.cdsap.daemonitor.distribution.DistributionChannel.DIRECT, buildInfo.distribution)
    }
}
