package io.github.cdsap.daemonitor.persistence

import io.github.cdsap.daemonitor.domain.model.ProcessType

/** A persisted process snapshot used by history and MCP queries. */
data class ProcessSample(
    val timestampMs: Long,
    val pid: Long,
    val parentPid: Long,
    val processType: ProcessType,
    val commandLine: String,
    val workingDirectory: String?,
    val projectPath: String?,
    val cpuPercent: Double?,
    val rssMemoryMb: Long,
    val maxHeapMb: Long?,
    val status: String,
    /** Live heap used (MB); null when unavailable — never coerced from missing to zero. */
    val heapUsedMb: Long? = null,
    val heapCommittedMb: Long? = null,
    val heapMaxMb: Long? = null,
    val heapSampledAtMs: Long? = null,
    val heapAvailable: Boolean = false,
    val virtualMemoryMb: Long? = null,
    val swapMemoryMb: Long? = null,
    val threadCount: Long? = null,
    val readBytes: Long? = null,
    val writeBytes: Long? = null,
    val readOperations: Long? = null,
    val writeOperations: Long? = null,
    val minorPageFaults: Long? = null,
    val majorPageFaults: Long? = null,
    val voluntaryContextSwitches: Long? = null,
    val involuntaryContextSwitches: Long? = null,
    val openFileDescriptors: Long? = null,
    val metaspaceUsedMb: Long? = null,
    val metaspaceCommittedMb: Long? = null,
    val youngGcCount: Long? = null,
    val youngGcTimeMs: Long? = null,
    val oldGcCount: Long? = null,
    val oldGcTimeMs: Long? = null,
    val javaVersion: String? = null,
    val javaVendor: String? = null,
    val activeProcessorCount: Long? = null,
)
