package io.github.cdsap.daemonitor

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class BuildInfoTest {
    @Test
    fun `loads version and commit generated by the build`() {
        val buildInfo = BuildInfo.current

        assertEquals("1.0.5", buildInfo.version)
        assertTrue(buildInfo.commit.matches(Regex("[0-9a-f]{7,40}|unknown")), buildInfo.commit)
    }
}
